export interface LabEquipmentData {
  _id: string;
  name: string;
  description: string;
  quantity: number;
  type: string;
  imageUrl?: string;
  _createdAt: string;
}

export const labEquipmentDummyData: LabEquipmentData[] = [
  {
    _id: "1a2b3c4d5e6f",
    name: "Centrifuge",
    description: "A device used to separate substances of different densities.",
    quantity: 3,
    type: "1.5 L capacity",
    imageUrl: "https://example.com/images/centrifuge.jpg",
    _createdAt: "2024-01-01T10:00:00Z",
  },
  {
    _id: "7g8h9i0j1k2l",
    name: "Microscope",
    description: "An optical instrument used to magnify small objects.",
    quantity: 10,
    type: "Optical equipment",
    imageUrl: "https://example.com/images/microscope.jpg",
    _createdAt: "2024-01-02T15:30:00Z",
  },
  {
    _id: "3m4n5o6p7q8r",
    name: "Analytical Balance",
    description: "A precision instrument for measuring mass.",
    quantity: 5,
    type: "200 g capacity",
    imageUrl: "https://example.com/images/analytical-balance.jpg",
    _createdAt: "2024-01-03T12:45:00Z",
  },
  {
    _id: "9s0t1u2v3w4x",
    name: "Bunsen Burner",
    description: "A common piece of lab equipment used for heating substances.",
    quantity: 15,
    type: "Heating equipment",
    imageUrl: "https://example.com/images/bunsen-burner.jpg",
    _createdAt: "2024-01-04T08:20:00Z",
  },
  {
    _id: "5y6z7a8b9c0d",
    name: "Graduated Cylinder",
    description: "A piece of laboratory glassware used to measure liquid volume.",
    quantity: 20,
    type: "500 mL capacity",
    imageUrl: "https://example.com/images/graduated-cylinder.jpg",
    _createdAt: "2024-01-05T16:10:00Z",
  },
  {
    _id: "11x2y3z4a5b",
    name: "Pipette",
    description: "A tool used to transfer small quantities of liquid accurately.",
    quantity: 30,
    type: "10 mL capacity",
    imageUrl: "https://example.com/images/pipette.jpg",
    _createdAt: "2024-01-06T09:40:00Z",
  },
  {
    _id: "12c3d4e5f6g",
    name: "Beaker",
    description: "A simple container for stirring, mixing, and heating liquids.",
    quantity: 25,
    type: "1 L capacity",
    imageUrl: "https://example.com/images/beaker.jpg",
    _createdAt: "2024-01-07T11:50:00Z",
  },
  {
    _id: "13h4i5j6k7l",
    name: "Erlenmeyer Flask",
    description: "A conical flask used for mixing chemicals without spilling.",
    quantity: 18,
    type: "250 mL capacity",
    imageUrl: "https://example.com/images/erlenmeyer-flask.jpg",
    _createdAt: "2024-01-08T13:15:00Z",
  },
  {
    _id: "14m5n6o7p8q",
    name: "Thermometer",
    description: "An instrument used to measure temperature.",
    quantity: 12,
    type: "Temperature measurement",
    imageUrl: "https://example.com/images/thermometer.jpg",
    _createdAt: "2024-01-09T14:25:00Z",
  },
  {
    _id: "15r6s7t8u9v",
    name: "Test Tube",
    description: "A small glass tube used to hold samples for experiments.",
    quantity: 50,
    type: "10 mL capacity",
    imageUrl: "https://example.com/images/test-tube.jpg",
    _createdAt: "2024-01-10T10:30:00Z",
  },
  {
    _id: "16w7x8y9z0a",
    name: "Hot Plate",
    description: "A device used to heat substances in a controlled manner.",
    quantity: 8,
    type: "Heating equipment",
    imageUrl: "https://example.com/images/hot-plate.jpg",
    _createdAt: "2024-01-11T11:00:00Z",
  },
  {
    _id: "17b8c9d0e1f",
    name: "Spectrophotometer",
    description: "An instrument used to measure the absorbance of light by a solution.",
    quantity: 2,
    type: "Light measurement",
    imageUrl: "https://example.com/images/spectrophotometer.jpg",
    _createdAt: "2024-01-12T12:20:00Z",
  },
  {
    _id: "18g9h0i1j2k",
    name: "Fume Hood",
    description: "A ventilated enclosure for safely working with hazardous substances.",
    quantity: 3,
    type: "Ventilation system",
    imageUrl: "https://example.com/images/fume-hood.jpg",
    _createdAt: "2024-01-13T14:50:00Z",
  },
  {
    _id: "19l0m1n2o3p",
    name: "pH Meter",
    description: "A device used to measure the acidity or alkalinity of a solution.",
    quantity: 7,
    type: "0-14 pH measurement",
    imageUrl: "https://example.com/images/ph-meter.jpg",
    _createdAt: "2024-01-14T16:30:00Z",
  },
  {
    _id: "20q1r2s3t4u",
    name: "Distillation Apparatus",
    description: "A setup used to separate mixtures based on boiling points.",
    quantity: 4,
    type: "5 L capacity",
    imageUrl: "https://example.com/images/distillation-apparatus.jpg",
    _createdAt: "2024-01-15T17:10:00Z",
  },
];
