import type { Metadata } from "next";
import { Manrope, Gabarito, Sora } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import React from "react";

const gabarito = Gabarito({
  variable: "--font-heading",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-paragraph",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InvenTrack | TMC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${sora.variable} ${gabarito.variable} antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
